<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
  
  </PropertyGroup>

  <PropertyGroup>
    <TrimMode>full</TrimMode>
    <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
    <TrimmerSingleWarn>false</TrimmerSingleWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="BenchmarkDotNet.Artifacts-1\**" />
    <Compile Remove="BenchmarkDotNet.Artifacts\**" />
    <EmbeddedResource Remove="BenchmarkDotNet.Artifacts-1\**" />
    <EmbeddedResource Remove="BenchmarkDotNet.Artifacts\**" />
    <None Remove="BenchmarkDotNet.Artifacts-1\**" />
    <None Remove="BenchmarkDotNet.Artifacts\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="System.Drawing.Common.xml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.IO.Hashing" Version="10.0.5" />
    <PackageReference Include="Microsoft.IO.RecyclableMemoryStream" Version="3.0.*" />
    <!--<PackageReference Include="microsoft.dotnet.ilcompiler" Version="10.0.5" />-->
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClassLibrary1\ClassLibraryForDeserialization.csproj" />
  </ItemGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="ClassLibraryForDeserialization" />
  </ItemGroup>

  <ItemGroup>
    <None Update="TestData\System.Drawing.Common.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
